"""Versioned Vietnamese scam scenario families derived from public advisories.

These are synthetic paraphrase specifications, not copies of advisory text or
victim messages. Each family has split-specific wording so evaluation does not
reuse the exact training template.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ScenarioTemplateSpec:
    key: str
    scenario: str
    train: str
    validation: str
    test: str
    signals: tuple[str, ...]
    is_phishing: bool = True
    train_extra: tuple[str, ...] = ()


EMERGING_SCAM_SPECS: tuple[ScenarioTemplateSpec, ...] = (
    ScenarioTemplateSpec(
        "vneid",
        "fake_vneid_biometric",
        "Cán bộ hỗ trợ VNeID yêu cầu cập nhật sinh trắc học bằng file tại {fake_url}. Cài ngay và đọc <OTP> để không khóa tài khoản.",
        "Trung tâm định danh thông báo hồ sơ sắp vô hiệu. Tải ứng dụng xác minh ngoài kho và gửi mã <OTP> trong {duration}.",
        "Nhân viên dịch vụ công yêu cầu kích hoạt căn cước mức mới qua {fake_url}; nếu chậm sẽ tạm dừng VNeID.",
        (
            "mao_danh_tham_quyen",
            "ap_luc_thoi_gian",
            "cai_app_ngoai",
            "yeu_cau_otp",
        ),
    ),
    ScenarioTemplateSpec(
        "sim",
        "fake_sim_update_call_forwarding",
        "Nhân viên nhà mạng báo SIM chưa chuẩn hóa. Bấm mã chuyển tiếp cuộc gọi và đọc <OTP> trong {duration} để tránh khóa số.",
        "Thuê bao sẽ bị cắt hôm nay. Hãy làm theo cú pháp kỹ thuật tôi gửi rồi cung cấp mã xác nhận <OTP>.",
        "Bộ phận viễn thông yêu cầu bật chuyển tiếp cuộc gọi để đồng bộ VNeID; hoàn tất ngay trước {deadline}.",
        ("mao_danh_tham_quyen", "ap_luc_thoi_gian", "yeu_cau_otp"),
    ),
    ScenarioTemplateSpec(
        "traffic",
        "fake_traffic_fine",
        "Cảnh sát giao thông thông báo xe có phạt nguội. Cài phần mềm tại {fake_url} và nộp phạt vào <ACCOUNT> trước {deadline}.",
        "Hồ sơ đổi giấy phép lái xe đang bị treo. Chuyển lệ phí vào tài khoản cán bộ <ACCOUNT> trong {duration}.",
        "Cổng giao thông yêu cầu mở link lạ để xử lý vi phạm và thanh toán gấp qua <ACCOUNT> hôm nay.",
        (
            "mao_danh_tham_quyen",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "cai_app_ngoai",
        ),
    ),
    ScenarioTemplateSpec(
        "kidnap",
        "online_kidnapping",
        "Công an nói em liên quan rửa tiền. Không gọi gia đình, vào phòng riêng, bật chia sẻ màn hình và chuyển tiền chứng minh vào <ACCOUNT>.",
        "Có lệnh bắt khẩn cấp. Cài Zoom, mở camera liên tục và giữ bí mật; trong {duration} nộp tiền xác minh vào <ACCOUNT>.",
        "Muốn chứng minh vô tội thì đến nơi vắng, không liên lạc với ai và chuyển <AMOUNT:trieu> ngay cho cơ quan điều tra.",
        (
            "mao_danh_tham_quyen",
            "yeu_cau_bi_mat",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "chuyen_kenh",
        ),
    ),
    ScenarioTemplateSpec(
        "deepfamily",
        "deepfake_relative",
        "Con đang gọi bằng số mượn vì máy hỏng. Đừng gọi lại số cũ, chuyển viện phí vào <ACCOUNT> ngay giúp con.",
        "Anh vừa gọi video rồi, em không cần xác minh thêm. Giữ kín và gửi <AMOUNT:trieu> vào <ACCOUNT> trong {duration}.",
        "Sếp đã gửi đoạn ghi âm duyệt khoản này. Không hỏi phòng kế toán, chuyển gấp vào <ACCOUNT> trước {deadline}.",
        ("yeu_cau_bi_mat", "ap_luc_thoi_gian", "tk_ca_nhan"),
    ),
    ScenarioTemplateSpec(
        "sextort",
        "deepfake_sextortion",
        "Tôi có video nhạy cảm của anh. Không được báo ai; chuyển <AMOUNT:trieu> vào <ACCOUNT> trước {deadline} nếu không sẽ phát tán.",
        "Ảnh riêng tư đã được gửi kèm. Muốn giữ danh dự thì liên hệ kín qua {channel} và nộp tiền trong {duration}.",
        "Clip của bạn sẽ gửi cho cơ quan và gia đình hôm nay. Giữ im lặng, chuyển tiền vào <ACCOUNT> để xóa.",
        ("yeu_cau_bi_mat", "ap_luc_thoi_gian", "tk_ca_nhan", "chuyen_kenh"),
    ),
    ScenarioTemplateSpec(
        "refund",
        "ecommerce_refund",
        "Nhân viên sàn báo đơn bị lỗi và sẽ hoàn tiền. Gửi mã <OTP> cho tôi trong {duration} để nhận lại tiền.",
        "Bộ phận chăm sóc khách hàng cần xác minh ví trước khi hoàn tiền. Chuyển sang {channel} và đọc mã xác nhận.",
        "Đơn hàng bị hủy, khoản hoàn sắp hết hạn. Cung cấp <OTP> ngay cho nhân viên để mở khóa ví.",
        (
            "mao_danh_tham_quyen",
            "ap_luc_thoi_gian",
            "chuyen_kenh",
            "yeu_cau_otp",
        ),
    ),
    ScenarioTemplateSpec(
        "shipper",
        "fake_shipper",
        "Shipper báo đơn chưa thanh toán. Chuyển phí giữ đơn vào <ACCOUNT> ngay rồi kết bạn {channel} để hủy đăng ký.",
        "Đơn giao nhầm đã kích hoạt hội viên. Muốn tránh trừ tiền hàng tháng, nộp phí xác minh vào <ACCOUNT> trong {duration}.",
        "Nhân viên giao hàng yêu cầu thanh toán trước vào tài khoản cá nhân và nhắn riêng để nhận lại phí.",
        ("ap_luc_thoi_gian", "tk_ca_nhan", "chuyen_kenh"),
    ),
    ScenarioTemplateSpec(
        "market",
        "fake_marketplace_deposit",
        "Món hàng giá rẻ chỉ giữ đến {deadline}. Chuyển cọc vào <ACCOUNT> ngay và trao đổi riêng qua {channel}.",
        "Cửa hàng sale sâu bất thường. Chuyển cọc vào tài khoản cá nhân <ACCOUNT> trong {duration}, không thanh toán qua sàn.",
        "Muốn giữ xe này phải chuyển <AMOUNT:trieu> vào tài khoản cá nhân hôm nay rồi rời khỏi ứng dụng.",
        (
            "loi_ich_bat_thuong",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "chuyen_kenh",
        ),
        train_extra=(
            "Cửa hàng giảm giá sâu nhưng không nhận thanh toán qua sàn. Hãy đặt cọc gấp vào <ACCOUNT> và nhắn riêng {channel}.",
            "Người bán hứa ưu đãi lớn nếu chuyển tiền giữ hàng vào tài khoản cá nhân trước khi xem.",
        ),
    ),
    ScenarioTemplateSpec(
        "travel",
        "fake_travel_ticket",
        "Combo du lịch giảm giá đặc biệt chỉ còn hôm nay. Đặt cọc vào <ACCOUNT> và nhắn {channel} để giữ chỗ.",
        "Vé máy bay rẻ hơn một nửa, cần chuyển đủ tiền trong {duration} vào tài khoản cá nhân.",
        "Phòng nghỉ lễ giá sốc sắp hết. Rời ứng dụng và thanh toán ngay qua <ACCOUNT> để nhận mã.",
        (
            "loi_ich_bat_thuong",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "chuyen_kenh",
        ),
    ),
    ScenarioTemplateSpec(
        "invest",
        "investment_crypto",
        "Chuyên gia cam kết lợi nhuận 30% mỗi tuần. Chuyển vốn vào <ACCOUNT> trước {deadline} và vào nhóm kín {channel}.",
        "Sàn AI bảo đảm thắng tuyệt đối, nạp <AMOUNT:trieu> trong {duration} để nhận tín hiệu nội bộ.",
        "Cơ hội tiền ảo không thể lỗ sắp đóng. Chuyển USDT vào ví cá nhân và chỉ trao đổi qua {channel}.",
        (
            "loi_ich_bat_thuong",
            "yeu_cau_bi_mat",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "chuyen_kenh",
        ),
    ),
    ScenarioTemplateSpec(
        "romance",
        "romance_investment",
        "Anh chỉ chia sẻ cơ hội đầu tư này với em. Giữ kín, nạp tiền vào <ACCOUNT> rồi sang {channel} để anh hướng dẫn.",
        "Mình sắp gặp nhau nên em hãy thử sàn chắc thắng này; đừng nói người thân và chuyển vốn hôm nay.",
        "Quà từ nước ngoài đang bị giữ. Muốn nhận thì chuyển phí vào <ACCOUNT> và chỉ liên lạc riêng với anh.",
        (
            "loi_ich_bat_thuong",
            "yeu_cau_bi_mat",
            "tk_ca_nhan",
            "chuyen_kenh",
        ),
    ),
    ScenarioTemplateSpec(
        "loan",
        "fake_loan_finance",
        "Công ty tài chính duyệt vay không cần hồ sơ. Cài app tại {fake_url} và chuyển phí giải ngân vào <ACCOUNT>.",
        "Khoản vay lãi suất cực thấp đã được duyệt; nộp phí bảo hiểm trong {duration} qua tài khoản cá nhân.",
        "Muốn nhận tiền ngay hôm nay hãy tải APK tín dụng, đóng phí mở hạn mức và nhắn riêng {channel}.",
        (
            "mao_danh_tham_quyen",
            "loi_ich_bat_thuong",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "cai_app_ngoai",
            "chuyen_kenh",
        ),
    ),
    ScenarioTemplateSpec(
        "recover",
        "account_recovery",
        "Kỹ thuật viên có thể lấy lại Facebook trong {duration}. Chuyển phí vào <ACCOUNT> và gửi mã <OTP> cho tôi.",
        "Tài khoản của bạn sắp bị xóa. Nhắn riêng {channel}, thanh toán phí xác minh rồi đọc mã đăng nhập.",
        "Đội hỗ trợ mạng xã hội yêu cầu cung cấp <OTP> ngay để mở khóa tài khoản bị chiếm.",
        (
            "mao_danh_tham_quyen",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "chuyen_kenh",
            "yeu_cau_otp",
        ),
    ),
    ScenarioTemplateSpec(
        "moneyback",
        "recovery_refund",
        "Đơn vị hỗ trợ cam kết lấy lại toàn bộ tiền đã mất. Chuyển phí hồ sơ vào <ACCOUNT> trước {deadline}.",
        "Quỹ bồi hoàn đã tìm thấy tiền bị treo; nộp phí xác minh trong {duration} để giải ngân.",
        "Luật sư mạng có thể thu hồi tiền lừa đảo 100%. Liên hệ kín {channel} và đóng phí trước.",
        (
            "mao_danh_tham_quyen",
            "loi_ich_bat_thuong",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "chuyen_kenh",
        ),
    ),
    ScenarioTemplateSpec(
        "charity",
        "fake_charity_hospital",
        "Bệnh viện kêu gọi cứu bệnh nhi trong hôm nay. Chuyển trực tiếp vào tài khoản cá nhân <ACCOUNT> càng sớm càng tốt.",
        "Quỹ cứu trợ khẩn cần tiền trước {deadline}. Xin gửi vào <ACCOUNT> của người phụ trách.",
        "Hoàn cảnh cấp cứu sắp hết thời gian điều trị. Hãy chuyển <AMOUNT:trieu> ngay vào tài khoản cá nhân.",
        ("mao_danh_tham_quyen", "ap_luc_thoi_gian", "tk_ca_nhan"),
    ),
    ScenarioTemplateSpec(
        "insurance",
        "fake_health_insurance",
        "Bảo hiểm xã hội thông báo được hoàn tiền. Cài ứng dụng tại {fake_url} và đọc <OTP> để nhận trong hôm nay.",
        "Thẻ bảo hiểm sắp khóa, cần cập nhật trên link lạ và cung cấp mã xác nhận trong {duration}.",
        "Nhân viên bảo hiểm yêu cầu bật chia sẻ màn hình để nhận khoản hỗ trợ trước {deadline}.",
        (
            "mao_danh_tham_quyen",
            "loi_ich_bat_thuong",
            "ap_luc_thoi_gian",
            "cai_app_ngoai",
            "yeu_cau_otp",
        ),
        train_extra=(
            "Cơ quan bảo hiểm yêu cầu nhận hỗ trợ bằng cách tải APK ngoài kho và gửi mã <OTP> ngay.",
            "Hồ sơ BHXH sắp hết hạn; bấm link cài phần mềm xác minh và làm theo hướng dẫn trong {duration}.",
        ),
    ),
    ScenarioTemplateSpec(
        "parcel",
        "fake_customs_parcel",
        "Hải quan đang giữ bưu kiện từ nước ngoài. Nộp phí vào <ACCOUNT> trong {duration} và không liên hệ hãng vận chuyển.",
        "Kiện quà có tiền mặt cần đóng thuế gấp trước {deadline}; chuyển vào tài khoản cán bộ <ACCOUNT>.",
        "Bưu phẩm của bạn liên quan hàng cấm. Giữ kín và thanh toán phí xử lý ngay qua <ACCOUNT>.",
        (
            "mao_danh_tham_quyen",
            "yeu_cau_bi_mat",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
        ),
    ),
    ScenarioTemplateSpec(
        "takeover",
        "social_account_takeover",
        "Tài khoản của tôi bị lỗi, đừng gọi lại. Chuyển tiền gấp vào <ACCOUNT> và giữ kín giúp tôi.",
        "Mình đổi số mới. Gửi mã <OTP> vừa nhận để mình vào lại nhóm và không báo quản trị viên.",
        "Sếp đang họp nên chỉ nhắn tin. Chuyển khoản bí mật trước {deadline} vào tài khoản này.",
        ("yeu_cau_bi_mat", "ap_luc_thoi_gian", "tk_ca_nhan", "yeu_cau_otp"),
    ),
    ScenarioTemplateSpec(
        "receipt",
        "fake_transfer_receipt",
        "Tôi đã chuyển thừa, biên lai ở đây. Hoàn lại ngay vào tài khoản khác <ACCOUNT> trước khi ngân hàng khóa.",
        "Ảnh báo giao dịch thành công rồi, hãy giao hàng ngay và chuyển phần chênh lệch vào <ACCOUNT>.",
        "Tiền đang treo nhưng hóa đơn đã xác nhận. Gửi lại khoản dư vào tài khoản cá nhân trong {duration}.",
        ("ap_luc_thoi_gian", "tk_ca_nhan"),
    ),
    ScenarioTemplateSpec(
        "qr",
        "malicious_qr_payment",
        "Quét mã QR mới để nhận hoàn tiền rồi chuyển phí xác minh vào <ACCOUNT> trước {deadline}.",
        "Mã thanh toán cũ bị lỗi. Quét QR tôi gửi và nộp lại ngay vào tài khoản cá nhân.",
        "Muốn mở khóa đơn hàng hãy quét mã ngoài ứng dụng, thanh toán trong {duration} và gửi ảnh biên lai.",
        ("ap_luc_thoi_gian", "tk_ca_nhan", "chuyen_kenh"),
    ),
    ScenarioTemplateSpec(
        "invoice",
        "business_invoice_change",
        "Sếp yêu cầu đổi tài khoản nhà cung cấp sang <ACCOUNT>. Giữ kín và chuyển khoản trước {deadline}.",
        "Thông tin hóa đơn đã đổi sang <ACCOUNT>. Giữ kín, không gọi xác nhận và chuyển tiền gấp vào tài khoản cá nhân mới.",
        "Khoản mua hàng mật cần xử lý trong {duration}; kế toán chuyển vào <ACCOUNT> và không hỏi bộ phận khác.",
        ("yeu_cau_bi_mat", "ap_luc_thoi_gian", "tk_ca_nhan"),
        train_extra=(
            "Giám đốc nhắn đổi số tài khoản thanh toán. Không xác minh lại, hãy gửi tiền vào <ACCOUNT> ngay hôm nay.",
            "Nhà cung cấp yêu cầu bí mật thay người nhận hóa đơn và chuyển khoản gấp vào tài khoản cá nhân.",
        ),
    ),
    ScenarioTemplateSpec(
        "childmodel",
        "fake_child_model",
        "Con bạn được chọn làm người mẫu nhí với cát-xê cao. Chuyển phí hồ sơ vào <ACCOUNT> hôm nay và vào nhóm {channel}.",
        "Không cần thử vai vẫn nhận hợp đồng quảng cáo; đóng tiền trang phục trong {duration} để giữ suất.",
        "Suất casting đặc biệt sắp hết. Chuyển cọc vào tài khoản cá nhân và trao đổi kín qua {channel}.",
        (
            "loi_ich_bat_thuong",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "chuyen_kenh",
        ),
    ),
    ScenarioTemplateSpec(
        "gamble",
        "gambling_tip",
        "Có số chắc trúng 100% tối nay. Chuyển phí vào <ACCOUNT> ngay và vào nhóm kín {channel}.",
        "Kèo nội bộ không thể thua chỉ mở trong {duration}; nộp tiền trước để nhận mã.",
        "Cam kết hoàn tiền nếu không trúng. Giữ bí mật và chuyển phí vào tài khoản cá nhân hôm nay.",
        (
            "loi_ich_bat_thuong",
            "yeu_cau_bi_mat",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "chuyen_kenh",
        ),
    ),
    ScenarioTemplateSpec(
        "overseasjob",
        "overseas_job_trafficking",
        "Việc nước ngoài lương <AMOUNT:trieu>, không cần hợp đồng. Giữ kín, chuyển phí xuất cảnh vào <ACCOUNT> và sang {channel}.",
        "Tuyển gấp làm việc biên giới thu nhập cao, không phỏng vấn; nộp cọc trong {duration}.",
        "Bao ăn ở, đi ngay hôm nay, không cần giấy tờ. Đừng nói gia đình và chuyển phí cho người dẫn đường.",
        (
            "loi_ich_bat_thuong",
            "yeu_cau_bi_mat",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "chuyen_kenh",
        ),
    ),
    ScenarioTemplateSpec(
        "rental",
        "fake_rental_deposit",
        "Phòng đẹp giá thấp chỉ còn một suất. Chuyển cọc vào <ACCOUNT> trước khi xem và nhắn riêng {channel}.",
        "Chủ nhà đang ở xa, cần đặt cọc trong {duration} để giữ căn hộ rẻ hơn thị trường.",
        "Không cần đến xem, chuyển <AMOUNT:trieu> vào tài khoản cá nhân hôm nay để nhận mã khóa.",
        (
            "loi_ich_bat_thuong",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "chuyen_kenh",
        ),
        train_extra=(
            "Căn hộ rẻ bất thường đang có nhiều người hỏi. Đặt cọc vào <ACCOUNT> trước khi đến xem.",
            "Chủ nhà ở xa yêu cầu chuyển tiền giữ phòng trong hôm nay và chỉ trao đổi qua {channel}.",
        ),
    ),
    ScenarioTemplateSpec(
        "ticket",
        "fake_event_ticket",
        "Vé concert hiếm bán rẻ, chỉ giữ đến {deadline}. Chuyển đủ tiền vào <ACCOUNT> rồi nhắn {channel}.",
        "Có vé sát sân khấu giá ưu đãi bất thường; đặt cọc ngay trong {duration}, không giao dịch qua sàn.",
        "Vé trận đấu sắp có người lấy. Chuyển tiền vào tài khoản cá nhân hôm nay để nhận mã điện tử.",
        (
            "loi_ich_bat_thuong",
            "ap_luc_thoi_gian",
            "tk_ca_nhan",
            "chuyen_kenh",
        ),
        train_extra=(
            "Vé sự kiện cháy hàng nhưng được bán rẻ bất thường. Chuyển cọc ngay vào <ACCOUNT>, không qua nền tảng.",
            "Người bán thúc giục thanh toán vé điện tử vào tài khoản cá nhân trước khi cho kiểm tra mã.",
        ),
    ),
    ScenarioTemplateSpec(
        "support",
        "tech_support_screen_share",
        "Kỹ thuật ngân hàng cần điều khiển màn hình để sửa lỗi. Cài app tại {fake_url}, giữ kín và làm ngay.",
        "Máy của bạn nhiễm mã độc. Tải phần mềm hỗ trợ ngoài kho trong {duration} và không tắt cuộc gọi.",
        "Nhân viên bảo mật yêu cầu bật quyền trợ năng, chia sẻ màn hình và chuyển sang {channel} riêng.",
        (
            "mao_danh_tham_quyen",
            "yeu_cau_bi_mat",
            "ap_luc_thoi_gian",
            "cai_app_ngoai",
            "chuyen_kenh",
        ),
        train_extra=(
            "Nhân viên an ninh yêu cầu chia sẻ màn hình và cài công cụ điều khiển ngoài cửa hàng ngay lập tức.",
            "Bộ phận kỹ thuật bắt bật quyền trợ năng, không ngắt cuộc gọi và chuyển sang nhóm riêng để xử lý.",
        ),
    ),
)


EMERGING_LEGITIMATE_SPECS: tuple[ScenarioTemplateSpec, ...] = (
    ScenarioTemplateSpec(
        "legit_vneid",
        "legitimate_vneid_notice",
        "Việc cập nhật VNeID chỉ thực hiện trong ứng dụng chính thức; cơ quan nhà nước không gửi APK và không hỏi OTP.",
        "Nếu cần chỉnh thông tin căn cước, hãy tự mở VNeID hoặc đến cơ quan công an, không làm theo link trong tin nhắn.",
        "Cảnh báo: không có cán bộ nào yêu cầu chia sẻ màn hình để cập nhật định danh điện tử.",
        (),
        False,
    ),
    ScenarioTemplateSpec(
        "legit_sim",
        "legitimate_sim_notice",
        "Nhà mạng khuyến cáo chỉ chuẩn hóa thuê bao trong ứng dụng chính thức hoặc tại điểm giao dịch.",
        "Không nhập cú pháp chuyển tiếp cuộc gọi theo hướng dẫn của người lạ và không đọc OTP cho nhân viên.",
        "Thuê bao của bạn hoạt động bình thường. Hãy tự kiểm tra thông tin trong ứng dụng nhà mạng.",
        (),
        False,
    ),
    ScenarioTemplateSpec(
        "legit_traffic",
        "legitimate_traffic_notice",
        "Cảnh sát giao thông không gọi điện yêu cầu chuyển tiền phạt nguội; người dân tự tra cứu trên cổng chính thức.",
        "Hồ sơ đổi giấy phép đã được tiếp nhận, không cần cài phần mềm hoặc thanh toán vào tài khoản cá nhân.",
        "Khi xử lý vi phạm, hãy đến đơn vị công an hoặc dùng cổng dịch vụ công đã tự truy cập.",
        (),
        False,
        train_extra=(
            "Thông báo phạt nguội thật không yêu cầu bấm link, cài ứng dụng hoặc chuyển tiền cho cán bộ.",
            "Người dân tự tra cứu vi phạm và đổi giấy phép trên cổng chính thức, không làm theo cuộc gọi lạ.",
            "Cơ quan công an cảnh báo không cung cấp thông tin và không thanh toán phạt qua tài khoản cá nhân.",
        ),
    ),
    ScenarioTemplateSpec(
        "legit_refund",
        "legitimate_ecommerce_refund",
        "Sàn đã hoàn tiền vào phương thức thanh toán ban đầu. Nhân viên không yêu cầu OTP.",
        "Yêu cầu trả hàng đã được ghi nhận trong ứng dụng; bạn không cần chuyển phí cho ai.",
        "Khoản hoàn sẽ tự xử lý trong ứng dụng chính thức, không cần kết bạn với nhân viên.",
        (),
        False,
    ),
    ScenarioTemplateSpec(
        "legit_shipper",
        "legitimate_delivery_notice",
        "Đơn hàng sẽ được giao trong hôm nay và thanh toán đúng số tiền hiển thị trên ứng dụng.",
        "Shipper đang trên đường đến. Nếu không nhận, bạn có thể hủy trực tiếp trong ứng dụng.",
        "Đơn giao không thành công sẽ được thử lại; không có phí hủy hội viên hoặc tài khoản cá nhân.",
        (),
        False,
    ),
    ScenarioTemplateSpec(
        "legit_market",
        "legitimate_marketplace",
        "Người bán đồng ý giao dịch và thanh toán hoàn toàn qua sàn, không yêu cầu đặt cọc riêng.",
        "Bạn có thể đến xem hàng rồi mới quyết định; không cần chuyển tiền giữ chỗ.",
        "Đơn mua được bảo vệ bởi nền tảng và người bán không yêu cầu rời ứng dụng.",
        (),
        False,
    ),
    ScenarioTemplateSpec(
        "legit_invest",
        "legitimate_investment_warning",
        "Cảnh báo đầu tư: không có lợi nhuận nào được bảo đảm và không chuyển tiền theo lời mời trên nhóm chat.",
        "Công ty chứng khoán khuyến nghị tự kiểm tra giấy phép; nhân viên không cam kết thắng.",
        "Biến động thị trường có thể gây thua lỗ. Không nạp tiền vào tài khoản cá nhân của người tư vấn.",
        (),
        False,
    ),
    ScenarioTemplateSpec(
        "legit_charity",
        "legitimate_charity_notice",
        "Quỹ công khai hồ sơ và tài khoản tổ chức trên website chính thức; người ủng hộ tự quyết định thời điểm.",
        "Bệnh viện xác nhận không kêu gọi chuyển tiền vào tài khoản cá nhân qua tin nhắn.",
        "Chương trình cứu trợ đã công bố báo cáo và không thúc ép quyên góp riêng.",
        (),
        False,
        train_extra=(
            "Tổ chức từ thiện khuyến nghị người dân tự xác minh hoàn cảnh và chỉ dùng tài khoản mang tên quỹ.",
            "Chương trình quyên góp không đặt thời hạn, không nhắn riêng và không nhận tiền qua cá nhân.",
            "Bệnh viện không kêu gọi viện phí bằng tin nhắn và không công bố tài khoản cá nhân để nhận hỗ trợ.",
            "Quỹ cứu trợ công khai sao kê, cho phép kiểm tra độc lập và không thúc ép chuyển khoản.",
        ),
    ),
    ScenarioTemplateSpec(
        "legit_parcel",
        "legitimate_customs_notice",
        "Hãng vận chuyển đã cập nhật trạng thái kiện hàng trong ứng dụng; không có yêu cầu chuyển tiền riêng.",
        "Thông báo hải quan chính thức có mã hồ sơ để tự tra cứu và không yêu cầu giữ bí mật.",
        "Bưu kiện đang làm thủ tục bình thường; mọi khoản phí hiển thị trên cổng của đơn vị vận chuyển.",
        (),
        False,
    ),
    ScenarioTemplateSpec(
        "legit_recovery",
        "legitimate_account_recovery",
        "Bạn đã yêu cầu đặt lại mật khẩu. Không chia sẻ mã khôi phục cho bất kỳ ai.",
        "Nếu không thực hiện yêu cầu này, hãy tự mở ứng dụng và khóa phiên đăng nhập.",
        "Mã đăng nhập chỉ nhập trên ứng dụng chính thức; bộ phận hỗ trợ sẽ không hỏi mã.",
        (),
        False,
    ),
    ScenarioTemplateSpec(
        "legit_qr",
        "legitimate_qr_payment",
        "Hóa đơn tại quầy đã tạo mã QR mang tên cửa hàng; vui lòng kiểm tra người nhận trước khi thanh toán.",
        "Mã QR này chỉ hiển thị số tiền mua hàng, không yêu cầu cài ứng dụng hay cung cấp OTP.",
        "Thanh toán đã hoàn tất trong ứng dụng ngân hàng; không cần gửi lại khoản chênh lệch.",
        (),
        False,
    ),
    ScenarioTemplateSpec(
        "legit_invoice",
        "legitimate_business_invoice",
        "Nhà cung cấp đề nghị xác nhận thay đổi tài khoản bằng cuộc gọi theo số trong hợp đồng trước khi thanh toán.",
        "Kế toán chưa chuyển khoản vì đang kiểm tra chéo thông tin hóa đơn với phòng mua hàng.",
        "Hóa đơn đến hạn vào tuần sau; mọi thay đổi người nhận phải có phê duyệt bằng văn bản.",
        (),
        False,
        train_extra=(
            "Phòng tài chính gọi lại số đã đăng ký để xác minh tài khoản nhà cung cấp trước khi duyệt lệnh.",
            "Mọi thay đổi thông tin nhận tiền phải được hai người phê duyệt, không xử lý chỉ từ tin nhắn của sếp.",
        ),
    ),
    ScenarioTemplateSpec(
        "legit_rental",
        "legitimate_rental",
        "Chủ nhà hẹn xem căn hộ và kiểm tra hợp đồng trước khi nhận tiền đặt cọc.",
        "Thông tin cho thuê đã xác minh trên nền tảng; khách không cần chuyển tiền trước khi xem.",
        "Hai bên sẽ ký biên bản và thanh toán tại địa chỉ căn hộ, không có yêu cầu gấp.",
        (),
        False,
    ),
    ScenarioTemplateSpec(
        "legit_ticket",
        "legitimate_event_ticket",
        "Vé được chuyển nhượng qua chức năng chính thức của ban tổ chức và thanh toán trên nền tảng.",
        "Mã vé chỉ xuất hiện sau khi giao dịch được hệ thống xác nhận; không cần đặt cọc riêng.",
        "Ban tổ chức cảnh báo không mua vé từ tài khoản cá nhân không thể xác minh.",
        (),
        False,
    ),
    ScenarioTemplateSpec(
        "legit_support",
        "legitimate_tech_support",
        "Nhân viên hỗ trợ hướng dẫn bạn tự mở phần cài đặt, không yêu cầu chia sẻ màn hình hoặc cài APK.",
        "Thiết bị đã cập nhật từ kho ứng dụng chính thức; không cần bật quyền trợ năng.",
        "Ngân hàng khuyến cáo không cho bất kỳ ai điều khiển điện thoại từ xa.",
        (),
        False,
    ),
)
